name: Validate and Build

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build addon with HEMTT
        uses: arma-actions/hemtt@master
        with:
          command: 'build --release'
      - uses: actions/upload-artifact@konradpabjan/v2-is-almost-here
        with:
          path: releases/@ZEN-*.zip
